### PR TITLE
fix: make the wall clock limit handle some edge cases correctly

### LINKED ISSUE #99: runtime closes connection when worker exceeds timeout
# Bug report

I'm running using the docker image v1.3.3 on a Mac M1.
When a worker is taking too long the runtime errors and stops working.  

- [x] I confirm this is a bug with Supabase, not with my own application. 
- [x] I confirm I have searched the [Docs](https://docs.supabase.com), GitHub [Discussions](https://github.com/supabase/supabase/discussions), and [Discord](https://discord.supabase.com). 

## Describe the bug

The worker has a timeout of 100 milliseconds.  
The hello-world worker is waiting for 1 second before returning a response.  

The error is:  
```
web_1  | main function started
web_1  | serving the request with /home/deno/functions/hello-world
web_1  | hello-world started
web_1  | Error: channel closed
web_1  |     at async UserWorker.fetch (ext:sb_user_workers/user_workers.js:54:21)
web_1  |     at async Server.<anonymous> (file:///home/deno/functions/main/index.ts:39:16)
web_1  |     at async Server.#respond (https://deno.land/std@0.131.0/http/server.ts:219:24)
web_1  | serving the request with /home/deno/functions/hello-world
web_1  | Error: channel closed
web_1  |     at async Function.create (ext:sb_user_workers/user_workers.js:80:21)
web_1  |     at async Server.<anonymous> (file:///home/deno/functions/main/index.ts:31:24)
web_1  |     at async Server.#respond (https://deno.land/std@0.131.0/http/server.ts:219:24)
```

The first request throws in `ext:sb_user_workers/user_workers.js:54:21`.   
Every subsequent request throws in `ext:sb_user_workers/user_workers.js:80:21`.  

## To Reproduce

I created a fork from the self hosted example.
https://github.com/EzzatOmar/self-hosted-edge-functions-demo

## System information

- OS: macOs
- Docker image: ghcr.io/supabase/edge-runtime:v1.3.5

### PR DESCRIPTION
**Pull request by nyannyacha**
## What kind of change does this PR introduce?

Bug fix

## Description

```typescript
// Inputs below will disable the wall clock limit.
const workerTimeoutMs = -999;
const workerTimeoutMs = -1;
const workerTimeoutMs = 0;
const worker = EdgeRuntime.userWorkers.create({
    ...,
    workerTimeoutMs
});
```

```typescript
// Worker is created and immediately terminated by the wall clock limit. However, if the script
// is lightweight enough to initialize quickly, the request can be processed before the worker exits.
const workerTimeoutMs = 1;
const worker = EdgeRuntime.userWorkers.create({
    ...,
    workerTimeoutMs
});
```

```typescript
// main.ts
const workerTimeoutMs = 2000;
const worker = EdgeRuntime.userWorkers.create({
    ...,
    workerTimeoutMs
});

// serve.ts
async function sleep(ms: number) {
    return new Promise(res => {
        setTimeout(() => {
            res(void 0);
        }, ms)
    });
}

// Wait 3000 ms on purpose. (Top-level await)
await sleep(3000);
Deno.serve((_req) => new Response("Hello, world"));

// Following case is also valid.
// Deno.serve(async () => {
//     await sleep(3000);
//     return new Response("Hello, world");
// });

// This script will be forced to exit after about 2000 ms with no requests processed.
```

Fixes #99

### CODE REVIEW

File: crates/base/src/rt_worker/implementation/default_handler.rs [hunk 1]
```diff
@@ -50,7 +53,23 @@ impl WorkerHandler for Worker {
                         }))
                     }
                 }
-                (Ok(()), _) => Ok(WorkerEvents::EventLoopCompleted(PseudoEvent {})),
+
+                (Ok(()), cpu_usage_ms) => {
+                    if created_rt.is_termination_requested.is_raised() {
+                        static EVENT_RECV_DEADLINE_DUR: Duration = Duration::from_secs(5);
```
Comment (laktek) [inline crates/base/src/rt_worker/implementation/default_handler.rs:59]: why do we need to wait for 5 seconds here?

It's nice we can account for CPU time usage on event loop completed events too.

**Review by laktek — APPROVED** [review]

File: crates/base/src/rt_worker/implementation/default_handler.rs (hunk 1 above)
Comment (nyannyacha) [reply crates/base/src/rt_worker/implementation/default_handler.rs:59]: @laktek It is an arbitrarily chosen time in case it might not be resolved forever.

Comment (nyannyacha) [reply crates/base/src/rt_worker/implementation/default_handler.rs:59]: Note:
I'm revisiting this part, and there's a possibility that if a supervisor unconditionally requests the isolate to terminate, it might not come to this branch, so it might be removed in the future.

Comment (laktek) [reply crates/base/src/rt_worker/implementation/default_handler.rs:59]: In that case can we add a comment on it?

Comment (nyannyacha) [reply crates/base/src/rt_worker/implementation/default_handler.rs:59]: @laktek 
Yes, I will add that.
