### PR TITLE
fix: audit unsafe op calls and implement `Deno.memoryUsage`

### LINKED ISSUE #209: TypeError: Deno.memoryUsage is not a function
**Describe the bug**
I'm attempting to get the `@sentry/node` SDK working in edge runtime. I see that `Deno.memoryUsage` got added to edge-runtime 3 months ago here https://github.com/supabase/edge-runtime/blame/01926fc73271f1834e49bf99d117f657ec4671a4/crates/node/polyfills/process.ts#L233 but on cli `1.99.10` the Sentry SDK fails to report events due to `TypeError: Deno.memoryUsage is not a function`.

Has `Deno.memoryUsage` not made it into the version of edge-runtime used by the cli yet?

**To Reproduce**

```ts
import * as Sentry from "https://esm.sh/@sentry/node?target=denonext&bundle=true"


Sentry.init({
    dsn: Deno.env.get("SENTRY_DSN"),
    debug: true,
    tracesSampleRate: 1,
})

Deno.serve(async req => {
    const transaction = Sentry.startTransaction({
        op: "test",
        name:  "testing",
    })
    transaction.finish()
     return new Response(JSON.stringify({success: true}), {
            headers: { "Content-Type": "application/json" },
            status: 200,
        })
})
```

observe that sentry debug logging outputs

```

[Error] Sentry Logger [warn]: w: Event processing pipeline threw an error, original event will not be sent. Details have been sent as a new event.
 Reason: TypeError: Deno.memoryUsage is not a function
     at https://esm.sh/v132/@sentry/node@7.71.0/denonext/node.bundle.mjs:32:14635
     at Array.<anonymous> (https://esm.sh/v132/@sentry/node@7.71.0/denonext/node.bundle.mjs:26:8995)
     at https://esm.sh/v132/@sentry/node@7.71.0/denonext/node.bundle.mjs:26:9718
     at Array.forEach (<anonymous>)
     at t._executeHandlers (https://esm.sh/v132/@sentry/node@7.71.0/denonext/node.bundle.mjs:26:9623)
     at t._setResult (https://esm.sh/v132/@sentry/node@7.71.0/denonext/node.bundle.mjs:26:9481)
     at _reject (https://esm.sh/v132/@sentry/node@7.71.0/denonext/node.bundle.mjs:26:9307)
     at Array.<anonymous> (https://esm.sh/v132/@sentry/node@7.71.0/denonext/node.bundle.mjs:26:8979)
     at https://esm.sh/v132/@sentry/node@7.71.0/denonext/node.bundle.mjs:26:9718
     at Array.forEach (<anonymous>) {
   name: "w",
   logLevel: "warn"
```

**Expected behavior**
Deno node apis should all work correctly

**Screenshots**
N/A

**Desktop (please complete the following information):**
 - OS: macos 13.5.2
 - Browser (if applicable) N/A
 - Version of CLI 1.99.10
 - Version of supabase-js (if applicable) N/A
 - Version of Node.js (if applicable) N/A

**Additional context**
N/A

### LINKED ISSUE #297: ReferenceError: Status is not defined when using Hocuspocus NPM package
# Bug report

- [x] I confirm this is a bug with Supabase, not with my own application. 
- [x] I confirm I have searched the [Docs](https://docs.supabase.com), GitHub [Discussions](https://github.com/supabase/supabase/discussions), and [Discord](https://discord.supabase.com). 

## Describe the bug

When trying to use the Hocuspocus package with the Supabase edge runtime, the following error is thrown:

```bash
ReferenceError: Status is not defined
    at Server.<anonymous> (file:///home/deno/main/index.ts:164:13)
    at eventLoopTick (ext:core/01_core.js:64:7)
    at async #respond (https://deno.land/std@0.182.0/http/server.ts:220:18)
serving the request with /home/deno/functions/document-sync
runtime has escaped from the event loop unexpectedly: event loop error: TypeError: Deno.addSignalListener is not a function
    at process.on (node:process:345:14)
    at Hocuspocus.listen (file:///tmp/sb-compile-edge-runtime/node_modules/localhost/@hocuspocus/server/2.11.3/dist/hocuspocus-server.esm.js:2509:21)
    at file:///home/deno/functions/document-sync/index.ts:5:8
failed to send request to user worker: connection error: Connection reset by peer (os error 104)
user worker failed to respond: connection error: Connection reset by peer (os error 104)
InvalidWorkerResponse: user worker failed to respond
    at async Promise.allSettled (index 1)
    at async UserWorker.fetch (ext:sb_user_workers/user_workers.js:70:21)
    at async Server.<anonymous> (file:///home/deno/main/index.ts:146:12)
    at async #respond (https://deno.land/std@0.182.0/http/server.ts:220:18) {
  name: "InvalidWorkerResponse"
}
```

## To Reproduce

The function file:
```ts
import { Server } from 'npm:@hocuspocus/server@latest'

const server = Server.configure({
  port: 8000,
})

server.listen()

```

## Expected behavior

The function is working when using the `deno run` command of the Deno CLI, but fails on the Supabase edge runtime, both in the hosted and in the local environment.

### PR DESCRIPTION
**Pull request by nyannyacha**
## What kind of change does this PR introduce?

Bug fix

## Description

This PR audit unsafe op calls in `node` crate and implements `Deno.memoryUsage`.

```typescript
import process from "node:process";

console.log(process.abort()); // disabled
console.log(Deno.writeFile) // blacklisted
console.log(Deno.cwd); // whitelisted
console.log(Deno.readFile); // whitelisted
console.log(Deno.readFileSync); // whitelisted
console.log(Deno.readTextFile); // whitelisted
console.log(Deno.readTextFileSync); // whitelisted
console.log(Deno.kill); // mocked
console.log(Deno.addSignalListener); // mocked
console.log(Deno.removeSignalListener); // mocked
console.log(Deno.execPath); // mocked (/bin/edge-runtime)
console.log(Deno.memoryUsage); // implemented
```

```
[Info] undefined
[Info] undefined
[Info] [Function: cwd]
[Info] [AsyncFunction: readFile]
[Info] [Function: readFileSync]
[Info] [AsyncFunction: readTextFile]
[Info] [Function: readTextFileSync]
[Info] [Function: MOCK_FN]
[Info] [Function: MOCK_FN]
[Info] [Function: MOCK_FN]
[Info] [Function: execPath]
[Info] [Function: memoryUsage]
```

Deno.memoryUsage
```
[Info] [Object: null prototype] {
  rss: 0,
  heapTotal: 11513856,
  heapUsed: 10047912,
  external: 14555
}
```

Fixes #297 
Fixes #209

### CODE REVIEW

File: crates/sb_core/lib.rs [hunk 1]
```diff
@@ -286,6 +283,30 @@ fn op_schedule_mem_check(state: &mut OpState) -> Result<(), AnyError> {
...
+
+#[op2]
+#[serde]
+fn op_runtime_memory_usage(scope: &mut v8::HandleScope) -> MemoryUsage {
+    let mut s = v8::HeapStatistics::default();
+
+    scope.get_heap_statistics(&mut s);
+
+    MemoryUsage {
+        rss: 0,
```
Comment (laktek) [inline crates/sb_core/lib.rs:303]: can you add an inline comment that this is hardcoded in edge-runtime

**Review by laktek — APPROVED** [review]
